spring:
  application:
    name: cloudsql-jpa
  profiles:
    include: gcp
---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
      sql:
        enabled: true
        instance-connection-name: ${CONNECTION_NAME} # gradlew clean bootRun --args=""--spring.cloud.gcp.sql.instance-connection-name=(gcloud sql instances describe my-mysql --format='value(connectionName)')""
        database-name: codelab
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME:root}
    password: ${PASSWORD:p@s$w0rd}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        use_sql_comments: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  sql:
    init:
      mode: embedded
      platform: mysql
      encoding: UTF-8
      schema-locations: classpath:db/schema.sql
      data-locations: classpath:db/data.sql
---
spring:
  config:
    activate:
      on-profile: dev # gradlew clean bootRun --args='--spring.profiles.active=dev'
  flyway:
    enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;database_to_upper=false;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
    database-platform: org.hibernate.dialect.H2Dialect
  data:
    jpa:
      repositories:
        bootstrap-mode: default